name: featbit
version: "3"
services:
  ui:
    image: featbit/featbit-ui:latest
    environment:
      - API_URL=https://<domain>:5000
      - DEMO_URL=https://featbit-samples.vercel.app
      - EVALUATION_URL=https://<domain>:5100
    depends_on:
      - api-server
    ports:
      - "8081:80"
    networks:
      - featbit-network

  api-server:
    image: featbit/featbit-api-server:latest
    environment:
      - MongoDb__ConnectionString=<connection-string>
      - MongoDb__Database=featbit
      - Redis__ConnectionString=redis:6379
      - OLAP__ServiceHost=http://da-server
    depends_on:
      - redis
      - da-server
    ports:
      - "5000:5000"
    networks:
      - featbit-network

  evaluation-server:
    image: featbit/featbit-evaluation-server:latest
    environment:
      - MongoDb__ConnectionString=<connection-string>
      - MongoDb__Database=featbit
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    ports:
      - "5100:5100"
    networks:
      - featbit-network

  da-server:
    image: featbit/featbit-data-analytics-server:latest
    depends_on:
      - redis
    ports:
      - "8200:80"
    networks:
      - featbit-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://admin:password@mongodb:27017
      MONGO_INITDB_DATABASE: featbit
      # MONGO_HOST: mongodb
      CHECK_DB_LIVNESS: false

  redis:
    image: bitnami/redis:6.2.10
    restart: on-failure
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - featbit-network
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

networks:
  featbit-network:
    name: featbit-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16

volumes:
  redis:
